import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavigationMenu from "./_components/NavigationMenu";
import ThanksMenu from "./_components/ThanksMenu";
import { ThemeProvider } from "@/providers/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kolay Eczane İzmir",
  description: "Generated by Ali Yorulmaz | With love and coffee.",
  generator: "Next.js",
  manifest: "/manifest.json",
  keywords: ["nextjs", "nextjs13", "next13", "pwa", "next-pwa"],
  authors: [
    { name: "Ali Yorulmaz" },
    {
      name: "Ali Yorulmaz",
      url: "https://www.linkedin.com/in/ali-yorulmaz-1a67a518a/",
    },
  ],
  icons: [
    { rel: "apple-touch-icon", url: "icons/icon-128x128.png" },
    { rel: "icon", url: "icons/icon-128x128.png" },
    { rel: "tablet-icon", url: "icons/icon-512x512.png" },
  ],
};

export const viewport = {
  themeColor: "#ffffff",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background antialiased flex flex-col",
          inter.className
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="absolute inset-0 -z-10 h-full w-full bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] dark:bg-[radial-gradient(#020817_1px,transparent_1px)]  [background-size:16px_16px]"></div>
          <div className="flex-grow">{children}</div>
          <footer className="w-full sticky bottom-14 pb-2 flex justify-center shadow-md">
            <ThanksMenu />
          </footer>
          <footer className="w-full sticky bottom-0 pb-2 flex justify-center shadow-md">
            <NavigationMenu />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}